### ISSUE TITLE
Missing libscanner_stdlib.so in CPU docker image

### ISSUE THREAD

**Issue by jblakley** [scanner-research/scanner#263]
Latest cpu docker image seems to be missing libscanner_stdlib.so.

Got the following error:

Connecting to Scanner database...
Traceback (most recent call last):
  File "smoketest.py", line 56, in <module>
    grpc_timeout=60)
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/database.py", line 188, in __init__
    self.start_master(master)
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/database.py", line 701, in start_master
    '{}/../scanner/stdlib/stdlib_pb2.py'.format(SCRIPT_DIR))
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/database.py", line 532, in load_op
    lambda: self._master.LoadOp(op_path, timeout=self._grpc_timeout))
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/database.py", line 366, in _try_rpc
    raise ScannerException(result.msg)
scannerpy.common.ScannerException: Failed to load op library: /usr/local/lib/python3.5/dist-packages/scannerpy/lib/libscanner_stdlib.so: cannot open shared object file: No such file or directory

Went into the container and the file was in fact missing.

Went back to an older image it and it worked.

**Comment by apoms** [comment]
Hi @jblakley, this issue is due to a temporary Docker image we pushed out to test the new version of Scanner that we are about to release. I'm rerunning our Docker built test right now to revert `latest` to the old working version. Should be fixed in about an hour. Thanks for catching that!

**Comment by jblakley** [comment]
Thanks, Alex!

**Comment by apoms** [comment]
Hi @jblakley, this should be fixed with the new version of Scanner. Closing for now.

**Comment by jblakley** [comment]
@apoms -- this problem still exists even with fresh pull of scannerresearch/scannertools:cpu-latest
Including smoketest.py -- uses old API -- is that an issue?

[smoketest.zip](https://github.com/scanner-research/scanner/files/3085012/smoketest.zip)

Current Output:
Using: star_wars_heros.mp4
Finding master IP...
Master ip: afb1a0094604711e9abb90aadf24e79a-328351843.us-east-1.elb.amazonaws.com:8080
Connecting to Scanner database...
Traceback (most recent call last):
  File "smoketest.py", line 54, in <module>
    grpc_timeout=60)
  File "/root/.local/lib/python3.5/site-packages/scannerpy/database.py", line 187, in __init__
    self.start_master(master)
  File "/root/.local/lib/python3.5/site-packages/scannerpy/database.py", line 703, in start_master
    '{}/../scanner/stdlib/stdlib_pb2.py'.format(SCRIPT_DIR))
  File "/root/.local/lib/python3.5/site-packages/scannerpy/database.py", line 534, in load_op
    lambda: self._master.LoadOp(op_path, timeout=self._grpc_timeout))
  File "/root/.local/lib/python3.5/site-packages/scannerpy/database.py", line 368, in _try_rpc
    raise ScannerException(result.msg)
scannerpy.common.ScannerException: Failed to load op library: /usr/local/lib/python3.5/dist-packages/scannerpy/lib/libscanner_stdlib.so: cannot open shared object file: No such file or directory
